//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_S02001_TEMP_IS
    {
        #region Primitive Properties
    
        public virtual string PONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PODate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DataVersion
        {
            get;
            set;
        }
    
        public virtual string AccessoriesNumberAI
        {
            get;
            set;
        }
    
        public virtual string AccessoriesNumberSERA
        {
            get;
            set;
        }
    
        public virtual string AccessoriesDescriptionSERA
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> QtyAccessories
        {
            get;
            set;
        }
    
        public virtual string CompanyCodeAI
        {
            get;
            set;
        }

        #endregion

    }
}
