//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_S02001_HS
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TransactionDataID
        {
            get { return _transactionDataID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_transactionDataID != value)
                    {
                        if (CUSTOM_TRANSACTIONDATA != null && CUSTOM_TRANSACTIONDATA.ID != value)
                        {
                            CUSTOM_TRANSACTIONDATA = null;
                        }
                        _transactionDataID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _transactionDataID;
    
        public virtual string PONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PODate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Version
        {
            get;
            set;
        }
    
        public virtual string CustomerNumber
        {
            get;
            set;
        }
    
        public virtual string KodeCabangAI
        {
            get;
            set;
        }
    
        public virtual string MaterialNumberSERA
        {
            get;
            set;
        }
    
        public virtual string MaterialDescriptionSERA
        {
            get;
            set;
        }
    
        public virtual string MaterialNumberAI
        {
            get;
            set;
        }
    
        public virtual string ColorDescSERA
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Quantity
        {
            get;
            set;
        }
    
        public virtual string NamaKaroseri
        {
            get;
            set;
        }
    
        public virtual string AlamatKaroseri
        {
            get;
            set;
        }
    
        public virtual string PIC
        {
            get;
            set;
        }
    
        public virtual string NoTelepon
        {
            get;
            set;
        }
    
        public virtual string BentukKaroseri
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> InfoPromiseDelivery
        {
            get;
            set;
        }
    
        public virtual string CustomerSTNKName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Title
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string KTPTDP
        {
            get;
            set;
        }
    
        public virtual string PostalCode
        {
            get;
            set;
        }
    
        public virtual string PartnerName
        {
            get;
            set;
        }
    
        public virtual string PartnerAddress
        {
            get;
            set;
        }
    
        public virtual string Telepon
        {
            get;
            set;
        }
    
        public virtual string City
        {
            get;
            set;
        }
    
        public virtual string RegionCode
        {
            get;
            set;
        }
    
        public virtual string PartnerPostalCode
        {
            get;
            set;
        }
    
        public virtual Nullable<double> Diskon
        {
            get;
            set;
        }
    
        public virtual Nullable<double> Pricing
        {
            get;
            set;
        }
    
        public virtual string CurrencyCode
        {
            get;
            set;
        }
    
        public virtual string dibuatOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> dibuatTanggal
        {
            get;
            set;
        }
    
        public virtual string diubahOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> diubahTanggal
        {
            get;
            set;
        }
    
        public virtual string Address2
        {
            get;
            set;
        }
    
        public virtual string Address3
        {
            get;
            set;
        }
    
        public virtual string Address4
        {
            get;
            set;
        }
    
        public virtual string Address5
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual CUSTOM_TRANSACTIONDATA CUSTOM_TRANSACTIONDATA
        {
            get { return _cUSTOM_TRANSACTIONDATA; }
            set
            {
                if (!ReferenceEquals(_cUSTOM_TRANSACTIONDATA, value))
                {
                    var previousValue = _cUSTOM_TRANSACTIONDATA;
                    _cUSTOM_TRANSACTIONDATA = value;
                    FixupCUSTOM_TRANSACTIONDATA(previousValue);
                }
            }
        }
        private CUSTOM_TRANSACTIONDATA _cUSTOM_TRANSACTIONDATA;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCUSTOM_TRANSACTIONDATA(CUSTOM_TRANSACTIONDATA previousValue)
        {
            if (previousValue != null && previousValue.CUSTOM_S02001_HS.Contains(this))
            {
                previousValue.CUSTOM_S02001_HS.Remove(this);
            }
    
            if (CUSTOM_TRANSACTIONDATA != null)
            {
                if (!CUSTOM_TRANSACTIONDATA.CUSTOM_S02001_HS.Contains(this))
                {
                    CUSTOM_TRANSACTIONDATA.CUSTOM_S02001_HS.Add(this);
                }
                if (TransactionDataID != CUSTOM_TRANSACTIONDATA.ID)
                {
                    TransactionDataID = CUSTOM_TRANSACTIONDATA.ID;
                }
            }
            else if (!_settingFK)
            {
                TransactionDataID = null;
            }
        }

        #endregion

    }
}
